### PR TITLE
Navigation style & functionality updates

### PR DESCRIPTION
**Pull request by flukeout**
* Removes sidebar image when not on the overview
* When switching between steps, the page scroll resets to top

### CODE REVIEW

**Comment by flukeout** [comment]
@chadsansing Boom!

**Comment by chadsansing** [comment]
Algebraic!

**Comment by flukeout** [comment]
@chadsansing Go ahead and merge if all good, I don't have access.

**Comment by chadsansing** [comment]
Merged. Will test and then close.

**Pull request merged**
